export const events = [
  {
    id: 'neobankers-brunch',
    title: 'Neobankers Brunch',
    time: '10:00–12:00 SGT · October 7',
    venue: 'Brunetti Oro · 6 Battery Road, Singapore',
    host: 'Wirex, Rigid.fi and Cardify Crypto',
    url: 'https://luma.com/vzpoa3ni',
    introduction: 'Day 3 opened with coffee and conversations about the next generation of crypto neobanks. The green wall and “Meet me in Milan” sign in the two original photos belong to this brunch, following the corrected event attribution in the field notes.',
    observation: 'The morning offered a useful starting point for the day’s larger question: how does stablecoin infrastructure become an everyday financial service? A wallet balance becomes more useful when a customer can spend it, convert it, receive local funds and understand the fees. The customer-facing brand depends on a substantial operating stack underneath.',
    photos: ['IMG_2642', 'IMG_2644'],
    people: 'The organizer listing names Tristyn Pawson and Max Narracott among its hosts. This was a networking brunch; the supplied notes do not identify a formal speaker session.',
    ecosystem: [
      ['Wirex', 'Consumer finance and payment infrastructure', 'The organizer describes Wirex as a stablecoin banking stack connecting digital balances to card spending and Visa/Mastercard network access.'],
      ['Rigid.fi', 'Issuer processing and controls', 'Rigid describes an API platform combining card processing, fraud decisions, KYC and a double-entry ledger. Its stablecoin offering links wallet funding, FX and card activity.'],
      ['Cardify Crypto', 'Product intelligence', 'The organizer identifies Cardify as a benchmarking resource for crypto neobanks, card fees, spend mechanics and liquidity rails.'],
      ['PayItFast · EasyOnRamp · KazePay · ConsistenC', 'Supporting ecosystem', 'Listed sponsors span payment products, regional ramps, crypto cards and business development. Together they illustrate the connections needed between distribution, acceptance and infrastructure.'],
    ],
    analysis: 'For a mature payment business, stablecoins may open new funding sources and corridors, but another card product alone does not guarantee growth. Our working hypothesis is that a better integrated service can expand useful payment volume per customer as well as reach new customers. Recipient access, pricing, reliability and support still determine adoption.',
    sources: [
      ['Event and host/sponsor descriptions', 'https://luma.com/vzpoa3ni'],
      ['Rigid product and ledger architecture', 'https://rigid.fi/'],
    ],
  },
  {
    id: 'sui-basecamp',
    title: 'Sui Basecamp 2026',
    time: 'October 7–8 program · Day 3 visit',
    venue: 'Marina Bay Sands · 10 Bayfront Avenue, Singapore',
    host: 'Sui',
    url: 'https://luma.com/suibasecamp2026',
    introduction: 'The next stop was Sui Basecamp. My impression was of a relaxed community with room to grow: an approachable environment for meeting builders and exploring ideas. A dedicated Sui and ecosystem edition will follow in a later log.',
    observation: 'That community atmosphere matters alongside the technology. Payment adoption requires developers, product teams and operators to work together; an accessible builder environment can make those conversations easier. This entry records the visit and its impression rather than reconstructing talks that were not captured in the supplied notes.',
    photos: [],
    people: 'The published lineup includes Evan Cheng and Adeniyi Abiodun of Mysten Labs, Matt Stafford of Circle, and Kimberly Logan of Walrus Foundation. These are program-listed speakers, not a claim that I attended each talk or met them.',
    ecosystem: [
      ['Sui · Mysten Labs', 'Execution and builders', 'Sui documentation describes an asset-oriented smart-contract platform using Move. Basecamp brings its builders and broader community together.'],
      ['Stablecoin payment tooling', 'Payment experience', 'Sui documents zero-gas transfers for eligible stablecoins. Eligibility and transaction conditions matter; this feature concerns on-chain transfer costs rather than the complete cost of a remittance.'],
      ['Walrus · Slush · Scallop · Bluefin', 'Data, wallets and finance', 'The organizer lists these ecosystem participants among Basecamp’s sponsors, illustrating the breadth beyond the base chain. The later special edition will examine their roles in detail.'],
    ],
    analysis: 'The question for our future Sui edition is how an easier on-chain experience connects to a complete business payment: issuer acceptance, wallet controls, FX, local credit and accounting. A welcoming community and simpler transfer UX are promising starting points; corridor delivery still needs its own evidence.',
    sources: [
      ['Basecamp program, lineup and sponsors', 'https://luma.com/suibasecamp2026'],
      ['Sui platform documentation', 'https://docs.sui.io/'],
      ['Sui transaction payment conditions', 'https://docs.sui.io/develop/transaction-payment/'],
    ],
  },
  {
    id: 'stablecon-salon',
    title: 'Stablecon Salon Happy Hour: Singapore vol 3',
    time: 'Next in the supplied Day 3 sequence · exact visit time not recorded',
    venue: 'Singapore · public listing withholds the address',
    host: 'Stablecon · powered by OpenFX and Faction',
    url: 'https://luma.com/j8huihey',
    introduction: 'The six photographs from this stop capture a plant-filled, glass-roofed setting and informal networking. Stablecon’s salon brought together people working on global money movement, stablecoins and FX infrastructure.',
    observation: 'The field notes point to a market opportunity: payment services are technically intensive, while mature customer acquisition can become harder. Stablecoins and new corridors may create another route to growth. The opportunity is strongest where a new rail solves a specific treasury or payment problem, rather than adding technology without changing the customer outcome.',
    photos: ['IMG_2670', 'IMG_2671', 'IMG_2672', 'IMG_2673', 'IMG_2674', 'IMG_2675'],
    people: 'The event listing names Clara Boh, Marc Palet and Rocco Puno among the hosts, alongside Stablecon, OpenFX and Faction. The supplied notes do not attribute particular remarks to them.',
    ecosystem: [
      ['Stablecon', 'Community and operator exchange', 'The salon format connects operators and investors around stablecoins, FX and cross-border payment infrastructure.'],
      ['OpenFX', 'FX liquidity and settlement', 'OpenFX describes round-the-clock FX infrastructure and a liquidity network for cross-border flows. The salon listing includes both fiat and stablecoins in its scope.'],
      ['Faction', 'Early-stage capital', 'Faction describes investments at Seed and Series A across blockchain infrastructure and applications, through equity and tokens. Its role here connects builders with venture capital.'],
    ],
    analysis: 'Liquidity and market access turn a token transfer into a practical corridor. The commercial questions are who buys or redeems the asset, who supplies local currency, what funds must be prefunded, and who handles a failed payout. For a startup, a narrow corridor with measurable economics is a stronger starting point than an undifferentiated promise of global reach.',
    sources: [
      ['Salon listing and hosts', 'https://luma.com/j8huihey'],
      ['OpenFX product and liquidity network', 'https://www.openfx.com/'],
      ['Faction investment focus', 'https://www.faction.vc/'],
    ],
  },
  {
    id: 'unprompted',
    title: 'UNPROMPTED: An Evening of Unscripted Conversations',
    time: '19:00 welcome drinks · 19:30 remarks · 19:40 short talks · 20:10 networking (published agenda)',
    venue: 'LeVeL33 · 8 Marina Boulevard, Tower 1, Singapore',
    host: 'Cobo and Sunrate · supported by Digital Assets Association and GFTN',
    url: 'https://luma.com/n3csj3ze',
    introduction: 'The evening moved to LeVeL33, with illuminated brewing tanks, the brewery bar and a gathering overlooking Marina Bay. The hosts convened banking, merchant, stablecoin, AI and infrastructure participants for short remarks and open conversations.',
    observation: 'This setting brought the day’s two-level model into focus. Many infrastructure providers remain less visible than the financial brands that use their capabilities. Those brands connect technology to enterprise relationships, trusted service delivery and local markets. Yet the boundary is porous: a provider can serve both the technical stack and the institutional customer.',
    photos: ['IMG_2676', 'IMG_2677', 'IMG_2678'],
    people: 'The agenda lists host remarks and two short talks, but does not name those speakers. No speaker identity or quotation is inferred from the venue photos.',
    ecosystem: [
      ['Cobo', 'Wallet, custody and operational infrastructure', 'Cobo offers wallet APIs, custody options, policy controls and stablecoin pay-in/payout tooling. It identifies Chainalysis and Elliptic as AML/KYT partners. This spans technical infrastructure and institutional operations.'],
      ['Sunrate', 'Business payments and treasury', 'Sunrate’s published products include international payments, local collection, commercial cards, FX and treasury tools. Its global interbank and local networks connect these services to business customers.'],
      ['Banking relationships', 'Institutional connectivity', 'The event’s Sunrate description names Citibank, Standard Chartered and J.P. Morgan as partners. These are Sunrate’s stated relationships; co-hosting alone does not establish a Cobo–Sunrate product integration.'],
      ['DAA · GFTN', 'Industry connections', 'Their support of the event places payment operators and digital asset builders alongside the wider financial and policy community.'],
    ],
    analysis: 'Cobo’s separate Settlement Network announcement provides a concrete parallel to the notes: counterparties retain their existing relationships and negotiate terms, while an execution service verifies and locks funds and records settlement milestones. Cobo describes manual fund checks and fragmented records as a bottleneck. That supports the automation problem observed today without attributing the announcement to a talk at this event.',
    sources: [
      ['UNPROMPTED agenda and host descriptions', 'https://luma.com/n3csj3ze'],
      ['Cobo wallet and payment capabilities', 'https://www.cobo.com/'],
      ['Sunrate products and local networks', 'https://www.sunrate.com/'],
      ['Cobo Settlement Network announcement', 'https://website.cobo.com/post/cobo-settlement-network-launch'],
    ],
  },
];
